In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')



In [2]:
np.random.seed(42)

X = np.random.rand(100, 4)

y = np.random.randint(0, 2, 100)

df = pd.DataFrame(X, columns=['Feature1', 'Feature2', 'Feature3', 'Feature4'])
df['Target'] = y

In [3]:
print(df.head())

   Feature1  Feature2  Feature3  Feature4  Target
0  0.374540  0.950714  0.731994  0.598658       0
1  0.156019  0.155995  0.058084  0.866176       1
2  0.601115  0.708073  0.020584  0.969910       0
3  0.832443  0.212339  0.181825  0.183405       0
4  0.304242  0.524756  0.431945  0.291229       1


In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)


KNeighborsClassifier()

In [6]:
y_pred = knn.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.35


In [7]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report


In [8]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.35


In [9]:
print("Precision:", precision_score(y_test, y_pred))

Precision: 0.4


In [10]:
print("Recall:", recall_score(y_test, y_pred))


Recall: 0.16666666666666666


In [11]:
print("F1 Score:", f1_score(y_test, y_pred))

F1 Score: 0.23529411764705882


In [12]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[ 5  3]
 [10  2]]


In [13]:
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Classification Report:
               precision    recall  f1-score   support

           0       0.33      0.62      0.43         8
           1       0.40      0.17      0.24        12

    accuracy                           0.35        20
   macro avg       0.37      0.40      0.34        20
weighted avg       0.37      0.35      0.32        20



In [14]:
from sklearn.svm import SVC
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, auc

In [15]:
np.random.seed(42)

X = np.random.rand(100, 4)

y = np.random.randint(0, 2, 100)

df = pd.DataFrame(X, columns=['Feature1', 'Feature2', 'Feature3', 'Feature4'])
df['Target'] = y

In [16]:
print(df.head())

   Feature1  Feature2  Feature3  Feature4  Target
0  0.374540  0.950714  0.731994  0.598658       0
1  0.156019  0.155995  0.058084  0.866176       1
2  0.601115  0.708073  0.020584  0.969910       0
3  0.832443  0.212339  0.181825  0.183405       0
4  0.304242  0.524756  0.431945  0.291229       1


In [17]:
model = SVC(kernel='linear')
model.fit(X, y)

SVC(kernel='linear')

In [18]:
y_pred = model.predict(X)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [19]:
new_points = np.array([[4, 6.5, 2, 3], [9, 8.8, 3.3, 4.1]])
new_preds = model.predict(new_points)
new_preds


array([0, 0], dtype=int32)

In [20]:
print(f"Accuracy Score: {accuracy_score(y, y_pred)}")
print(f"Precision: {precision_score(y, y_pred)}")
print(f"Recall: {recall_score(y, y_pred)}")
print(f"F1 Score: {f1_score(y, y_pred)}")

Accuracy Score: 0.57
Precision: 0.0
Recall: 0.0
F1 Score: 0.0


In [21]:
print("Confusion Matrix:\n", confusion_matrix(y, y_pred))
print("\nClassification Report:\n", classification_report(y, y_pred))

Confusion Matrix:
 [[57  0]
 [43  0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.57      1.00      0.73        57
           1       0.00      0.00      0.00        43

    accuracy                           0.57       100
   macro avg       0.28      0.50      0.36       100
weighted avg       0.32      0.57      0.41       100

